//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.CrmLogServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CrmLogServices.ICrmLogService")]
    public interface ICrmLogService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmLogService/AddLog", ReplyAction="http://tempuri.org/ICrmLogService/AddLogResponse")]
        void AddLog(string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICrmLogService/AddLog", ReplyAction="http://tempuri.org/ICrmLogService/AddLogResponse")]
        System.Threading.Tasks.Task AddLogAsync(string content);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICrmLogServiceChannel : test.CrmLogServices.ICrmLogService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CrmLogServiceClient : System.ServiceModel.ClientBase<test.CrmLogServices.ICrmLogService>, test.CrmLogServices.ICrmLogService {
        
        public CrmLogServiceClient() {
        }
        
        public CrmLogServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CrmLogServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrmLogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CrmLogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddLog(string content) {
            base.Channel.AddLog(content);
        }
        
        public System.Threading.Tasks.Task AddLogAsync(string content) {
            return base.Channel.AddLogAsync(content);
        }
    }
}
