//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestWebServiceConsole.WS.SR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS.SR.TestWebServiceSoap")]
    public interface TestWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        // CODEGEN: Generating message contract since message HelloWorldWithUserNameAndPassWordRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithUserNameAndPassWord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordResponse HelloWorldWithUserNameAndPassWord(TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithUserNameAndPassWord", ReplyAction="*")]
        System.Threading.Tasks.Task<TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordResponse> HelloWorldWithUserNameAndPassWordAsync(TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithLog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorldWithLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithLog", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldWithLogAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithLog2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorldWithLog2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorldWithLog2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldWithLog2Async();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MySoapHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PassWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
                this.RaisePropertyChanged("PassWord");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldWithUserNameAndPassWord", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HelloWorldWithUserNameAndPassWordRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public TestWebServiceConsole.WS.SR.MySoapHeader MySoapHeader;
        
        public HelloWorldWithUserNameAndPassWordRequest() {
        }
        
        public HelloWorldWithUserNameAndPassWordRequest(TestWebServiceConsole.WS.SR.MySoapHeader MySoapHeader) {
            this.MySoapHeader = MySoapHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldWithUserNameAndPassWordResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class HelloWorldWithUserNameAndPassWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string HelloWorldWithUserNameAndPassWordResult;
        
        public HelloWorldWithUserNameAndPassWordResponse() {
        }
        
        public HelloWorldWithUserNameAndPassWordResponse(string HelloWorldWithUserNameAndPassWordResult) {
            this.HelloWorldWithUserNameAndPassWordResult = HelloWorldWithUserNameAndPassWordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TestWebServiceSoapChannel : TestWebServiceConsole.WS.SR.TestWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TestWebServiceSoapClient : System.ServiceModel.ClientBase<TestWebServiceConsole.WS.SR.TestWebServiceSoap>, TestWebServiceConsole.WS.SR.TestWebServiceSoap {
        
        public TestWebServiceSoapClient() {
        }
        
        public TestWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TestWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TestWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordResponse TestWebServiceConsole.WS.SR.TestWebServiceSoap.HelloWorldWithUserNameAndPassWord(TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordRequest request) {
            return base.Channel.HelloWorldWithUserNameAndPassWord(request);
        }
        
        public string HelloWorldWithUserNameAndPassWord(TestWebServiceConsole.WS.SR.MySoapHeader MySoapHeader) {
            TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordRequest inValue = new TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordRequest();
            inValue.MySoapHeader = MySoapHeader;
            TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordResponse retVal = ((TestWebServiceConsole.WS.SR.TestWebServiceSoap)(this)).HelloWorldWithUserNameAndPassWord(inValue);
            return retVal.HelloWorldWithUserNameAndPassWordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordResponse> TestWebServiceConsole.WS.SR.TestWebServiceSoap.HelloWorldWithUserNameAndPassWordAsync(TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordRequest request) {
            return base.Channel.HelloWorldWithUserNameAndPassWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordResponse> HelloWorldWithUserNameAndPassWordAsync(TestWebServiceConsole.WS.SR.MySoapHeader MySoapHeader) {
            TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordRequest inValue = new TestWebServiceConsole.WS.SR.HelloWorldWithUserNameAndPassWordRequest();
            inValue.MySoapHeader = MySoapHeader;
            return ((TestWebServiceConsole.WS.SR.TestWebServiceSoap)(this)).HelloWorldWithUserNameAndPassWordAsync(inValue);
        }
        
        public string HelloWorldWithLog() {
            return base.Channel.HelloWorldWithLog();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldWithLogAsync() {
            return base.Channel.HelloWorldWithLogAsync();
        }
        
        public string HelloWorldWithLog2() {
            return base.Channel.HelloWorldWithLog2();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldWithLog2Async() {
            return base.Channel.HelloWorldWithLog2Async();
        }
    }
}
